auteur = "Lili Ricke"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "/images/Kartoffelpflanze.jpg"
description = "Description"
edition = "Fabrique"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "CC BY-NC-SA"
logo = "images/Kartoffelpflanze.jpg"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = "Image d'un plant de pomme de terre"
titre = "La Kartoffel"